# Generated by Django 4.1.6 on 2023-02-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
