# Generated by Django 4.1.7 on 2023-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ordemdeproducao_delete_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OrdemdeProducao',
        ),
    ]
