# Generated by Django 4.1.7 on 2023-04-08 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pessoa_delete_ordemdeproducao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
