# Generated by Django 4.1.7 on 2023-04-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pessoa_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='op',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(default='default_value', max_length=10),
        ),
    ]
