# Generated by Django 4.1.7 on 2023-04-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pessoa_nome_pessoa_op_alter_pessoa_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='numero',
            new_name='article',
        ),
    ]
