# Generated by Django 4.1.7 on 2023-04-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_numero_pessoa_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='article',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
