# Generated by Django 4.1.7 on 2023-04-08 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pessoa_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='approval_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='date_payment',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='date_shipment',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='first_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nf_fornecida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nf_ind',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nf_ret',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='preview_payment',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='second_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='third_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='timemoney',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='total_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='value_pieces',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='article',
            field=models.CharField(default='', max_length=10),
        ),
    ]
