# Generated by Django 4.2 on 2023-04-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pessoa_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='payment_confirmed',
            field=models.CharField(max_length=12),
        ),
    ]
