# Generated by Django 4.2.2 on 2024-03-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_payment_confirmed_pessoa_payment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Op',
        ),
    ]
