# Generated by Django 4.2.2 on 2024-03-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_pessoa_op'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Op',
            new_name='Pessoa',
        ),
    ]
